#! /bin/sh
echo "start..."

ovs-vsctl add-port s2 vboxnet0
ovs-vsctl add-port s3 vboxnet1
ovs-vsctl add-port s4 vboxnet2

ovs-ofctl add-flow s2 in_port=1,actions=output:2
ovs-ofctl add-flow s2 in_port=2,actions=output:controller
ovs-ofctl add-flow s3 in_port=1,actions=output:1
ovs-ofctl add-flow s3 in_port=2,actions=output:controller
ovs-ofctl add-flow s4 in_port=1,actions=output:1
ovs-ofctl add-flow s4 in_port=2,actions=output:controller

ovs-ofctl add-flow s3 in_port=2,actions=mod_nw_dst:10.0.0.3,mod_dl_dst:00:00:00:00:00:03,output:1
ovs-ofctl add-flow s3 in_port=1,actions=mod_nw_src:10.0.0.2,mod_dl_src:00:00:00:00:00:02,output:2

ovs-ofctl add-flow s4 in_port=2,actions=mod_nw_dst:10.0.0.4,mod_dl_dst:00:00:00:00:00:04,output:1
ovs-ofctl add-flow s4 in_port=1,actions=mod_nw_src:10.0.0.2,mod_dl_src:00:00:00:00:00:02,output:2


ovs-ofctl add-flow s3 in_port=2,actions=mod_nw_dst:10.0.0.3,mod_dl_dst:00:00:00:00:00:03,output:1

ovs-ofctl add-flow s3 in_port=1,actions=mod_nw_src:10.0.0.2,mod_dl_src:00:00:00:00:00:02,output:2

chmod 777 ovs

