#! /bin/sh
echo "start..."

ovs-vsctl add-port s0 vboxnet0
ovs-vsctl add-port s1 vboxnet1
ovs-vsctl add-port s2 vboxnet2
ovs-vsctl add-port s3 vboxnet3

# in
ovs-ofctl add-flow s1 in_port=1,actions=output:2

ovs-ofctl add-flow s2 in_port=1,actions=mod_nw_dst:192.168.56.102,mod_dl_dst:00:00:00:00:00:0b,output:2

ovs-ofctl add-flow s3 in_port=1,actions=mod_nw_dst:192.168.56.103,mod_dl_dst:00:00:00:00:00:0c,output:2

# out
ovs-ofctl add-flow s1 in_port=2,actions=output:controller

ovs-ofctl add-flow s2 in_port=2,actions=mod_nw_src:192.168.56.101,mod_dl_src:00:00:00:00:00:0a,output:controller

ovs-ofctl add-flow s3 in_port=2,actions=mod_nw_src:192.168.56.101,mod_dl_src:00:00:00:00:00:0a,output:controller

chmod 777 ovs-test

