#! /bin/sh
echo "start..."

ovs-vsctl add-port s0 vmnet0
ovs-vsctl add-port s1 vmnet1
ovs-vsctl add-port s2 vmnet2
ovs-vsctl add-port s3 vmnet3

# in

ovs-ofctl add-flow s0 in_port=1,actions=output:4

ovs-ofctl add-flow s1 in_port=1,actions=output:2


# out
ovs-ofctl add-flow s0 in_port=4,actions=output:1

ovs-ofctl add-flow s1 in_port=2,actions=output:controller

chmod 777 ovs-one

