#! /bin/sh
echo "start..."

ovs-vsctl add-port s1 vboxnet0
ovs-vsctl add-port s0 vboxnet1

ovs-ofctl add-flow s0 in_port=1,actions=output:2
ovs-ofctl add-flow s0 in_port=2,actions=output:1
ovs-ofctl add-flow s1 in_port=1,actions=output:2
ovs-ofctl add-flow s1 in_port=2,actions=output:1

chmod 777 ovs-ping

