#! /bin/sh
echo "start..."

ovs-ofctl add-flow s1 in_port=1,actions=output:flood
ovs-ofctl add-flow s1 in_port=2,actions=output:1
ovs-ofctl add-flow s1 in_port=3,actions=output:1
ovs-ofctl add-flow s1 in_port=4,actions=output:1
ovs-ofctl add-flow s2 in_port=1,actions=output:2
ovs-ofctl add-flow s2 in_port=2,actions=output:1
ovs-ofctl add-flow s3 in_port=1,actions=output:2
ovs-ofctl add-flow s3 in_port=2,actions=output:1

chmod 777 ovs

