#! /bin/sh
echo "start..."

ovs-ofctl add-flow s1 in_port=1,actions=output:flood
ovs-ofctl add-flow s1 in_port=2,actions=output:1
ovs-ofctl add-flow s1 in_port=3,actions=output:1
ovs-ofctl add-flow s1 in_port=4,actions=output:1
ovs-ofctl add-flow s2 in_port=1,actions=output:2
ovs-ofctl add-flow s2 in_port=2,actions=output:1
ovs-ofctl add-flow s3 in_port=1,actions=output:2
ovs-ofctl add-flow s3 in_port=2,actions=output:1
ovs-ofctl add-flow s4 in_port=1,actions=output:2
ovs-ofctl add-flow s4 in_port=2,actions=output:1

ovs-ofctl add-flow s3 in_port=2,actions=mod_nw_dst:10.0.0.3,mod_dl_dst:00:00:00:00:00:03,output:1

ovs-ofctl add-flow s3 in_port=1,actions=mod_nw_src:10.0.0.2,mod_dl_src:00:00:00:00:00:02,output:2

chmod 777 ovs

